"""Remove notification table

Revision ID: 06f000f4a9c3
Revises: 0dc92dec7f09
Create Date: 2024-09-20 07:50:37.414323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06f000f4a9c3'
down_revision = '0dc92dec7f09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
