"""add wallet network

Revision ID: 28d9d3e43f1c
Revises: f1082459981d
Create Date: 2024-11-12 06:39:29.379406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28d9d3e43f1c'
down_revision = 'f1082459981d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_wallets', sa.Column('wallet_network', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin_wallets', 'wallet_network')
    # ### end Alembic commands ###
