"""update User table 

Revision ID: 722f8b2a26b4
Revises: a6bba32cbcfa
Create Date: 2024-10-16 14:25:47.870599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '722f8b2a26b4'
down_revision = 'a6bba32cbcfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_admin')
    # ### end Alembic commands ###
