"""add wallet_symbol to wallet table

Revision ID: 73915ee085e7
Revises: ee93bf50711c
Create Date: 2024-09-24 12:02:52.867734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73915ee085e7'
down_revision = 'ee93bf50711c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallet', sa.Column('wallet_symbol', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wallet', 'wallet_symbol')
    # ### end Alembic commands ###
