"""update user table (correct mispelling) 

Revision ID: 78f7f59fbd9a
Revises: e49d96d941be
Create Date: 2024-09-27 11:08:40.784609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78f7f59fbd9a'
down_revision = 'e49d96d941be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
