"""Added tables

Revision ID: 86a5940d33d5
Revises: 
Create Date: 2024-09-13 23:50:35.749858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86a5940d33d5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_code', sa.String(length=250), nullable=True),
    sa.Column('country_name', sa.String(length=250), nullable=True),
    sa.Column('country_currency', sa.String(length=250), nullable=True),
    sa.Column('country_capital', sa.String(length=250), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('last_updated', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country_name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=250), nullable=True),
    sa.Column('msisdn', sa.String(length=250), nullable=True),
    sa.Column('password', sa.String(length=350), nullable=True),
    sa.Column('referral_id', sa.String(length=250), nullable=True),
    sa.Column('first_name', sa.String(length=350), nullable=True),
    sa.Column('last_name', sa.String(length=350), nullable=True),
    sa.Column('country', sa.String(length=350), nullable=True),
    sa.Column('language', sa.String(length=350), nullable=True),
    sa.Column('isDeactivated', sa.Boolean(), nullable=True),
    sa.Column('isEmailVerified', sa.Boolean(), nullable=True),
    sa.Column('isMsisdnVerified', sa.Boolean(), nullable=True),
    sa.Column('has_email_notification_enabled', sa.Boolean(), nullable=True),
    sa.Column('deactivate_reason', sa.String(length=450), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('last_updated', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('msisdn'),
    sa.UniqueConstraint('referral_id')
    )
    op.create_table('audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=350), nullable=True),
    sa.Column('data', sa.JSON(none_as_null=True), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('last_updated', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('confirmation_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=150), nullable=True),
    sa.Column('msisdn', sa.String(length=150), nullable=True),
    sa.Column('counter', sa.Integer(), nullable=True),
    sa.Column('expiration', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('last_updated', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('referral',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('referrer_id', sa.Integer(), nullable=False),
    sa.Column('referred_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('last_updated', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['referred_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['referrer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.Column('state_name', sa.String(length=250), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('last_updated', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('state_name')
    )
    op.create_table('wallet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('wallet_type', sa.String(length=350), nullable=True),
    sa.Column('wallet_name', sa.String(length=350), nullable=True),
    sa.Column('wallet_id', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('last_updated', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wallet_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wallet')
    op.drop_table('state')
    op.drop_table('referral')
    op.drop_table('confirmation_code')
    op.drop_table('audit')
    op.drop_table('user')
    op.drop_table('country')
    # ### end Alembic commands ###
