"""add coins table & update wallet tables

Revision ID: 92c45023e722
Revises: b785acb34471
Create Date: 2024-09-24 12:28:24.808164

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '92c45023e722'
down_revision = 'b785acb34471'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('wallet', sa.Column('coin_id', sa.Integer(), nullable=True))
    # op.create_foreign_key(None, 'wallet', 'coins', ['coin_id'], ['id'])
    # op.drop_column('wallet', 'wallet_name')
    # op.drop_column('wallet', 'wallet_type')
    # op.drop_column('wallet', 'wallet_symbol')
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallet', sa.Column('wallet_symbol', mysql.TEXT(), nullable=True))
    op.add_column('wallet', sa.Column('wallet_type', mysql.VARCHAR(length=350), nullable=True))
    op.add_column('wallet', sa.Column('wallet_name', mysql.VARCHAR(length=350), nullable=True))
    op.drop_constraint(None, 'wallet', type_='foreignkey')
    op.drop_column('wallet', 'coin_id')
    # ### end Alembic commands ###
