"""add balance to wallet

Revision ID: 97cb7e47221c
Revises: d4f988801197
Create Date: 2024-09-25 16:06:02.675960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97cb7e47221c'
down_revision = 'd4f988801197'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallet', sa.Column('balance', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wallet', 'balance')
    # ### end Alembic commands ###
