"""add rate column to coins

Revision ID: a453938637d7
Revises: ab37075b779f
Create Date: 2024-11-09 03:08:54.622977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a453938637d7'
down_revision = 'ab37075b779f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coins', sa.Column('rate', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coins', 'rate')
    # ### end Alembic commands ###
