"""update AdminWallet table

Revision ID: a6bba32cbcfa
Revises: 78f7f59fbd9a
Create Date: 2024-09-27 11:12:13.002588

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a6bba32cbcfa'
down_revision = '78f7f59fbd9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_wallets', sa.Column('coin_id', sa.Integer(), nullable=True))
    op.drop_index('name', table_name='admin_wallets')
    op.create_foreign_key(None, 'admin_wallets', 'coins', ['coin_id'], ['id'])
    op.drop_column('admin_wallets', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_wallets', sa.Column('name', mysql.TEXT(), nullable=True))
    op.drop_constraint(None, 'admin_wallets', type_='foreignkey')
    op.create_index('name', 'admin_wallets', ['name'], unique=False)
    op.drop_column('admin_wallets', 'coin_id')
    # ### end Alembic commands ###
