"""add coins table & update wallet tables

Revision ID: adbe3ff335c0
Revises: 92c45023e722
Create Date: 2024-09-24 12:32:45.033341

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'adbe3ff335c0'
down_revision = '92c45023e722'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_foreign_key(None, 'wallet', 'coins', ['coin_id'], ['id'])
    # op.drop_column('wallet', 'wallet_symbol')
    # op.drop_column('wallet', 'wallet_type')
    # op.drop_column('wallet', 'wallet_name')
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallet', sa.Column('wallet_name', mysql.VARCHAR(length=350), nullable=True))
    op.add_column('wallet', sa.Column('wallet_type', mysql.VARCHAR(length=350), nullable=True))
    op.add_column('wallet', sa.Column('wallet_symbol', mysql.TEXT(), nullable=True))
    op.drop_constraint(None, 'wallet', type_='foreignkey')
    # ### end Alembic commands ###
