"""remove wallet table

Revision ID: e09e1041f8f4
Revises: adbe3ff335c0
Create Date: 2024-09-24 21:17:52.130048

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e09e1041f8f4'
down_revision = 'adbe3ff335c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('wallet_id', table_name='wallet')
    op.drop_table('wallet')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallet',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('wallet_type', mysql.VARCHAR(length=350), nullable=True),
    sa.Column('wallet_name', mysql.VARCHAR(length=350), nullable=True),
    sa.Column('wallet_id', mysql.TEXT(), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('last_updated', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('wallet_symbol', mysql.TEXT(), nullable=True),
    sa.Column('coin_id', mysql.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='wallet_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='latin1_swedish_ci',
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('wallet_id', 'wallet', ['wallet_id'], unique=False)
    # ### end Alembic commands ###
