"""update transaction, user, coins, wallet table

Revision ID: e49d96d941be
Revises: 2dfc867b7422
Create Date: 2024-09-27 11:06:15.065153

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e49d96d941be'
down_revision = '2dfc867b7422'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_wallets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('wallet_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('last_updated', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('transactions', sa.Column('sender_id', sa.Integer(), nullable=True))
    op.add_column('transactions', sa.Column('receiver_id', sa.Integer(), nullable=True))
    op.add_column('transactions', sa.Column('coin_id', sa.Integer(), nullable=True))
    op.add_column('transactions', sa.Column('receiver_address', sa.Text(), nullable=True))
    op.add_column('transactions', sa.Column('receiver_fee', sa.Float(), nullable=True))
    op.add_column('transactions', sa.Column('sender_fee', sa.Float(), nullable=True))
    op.add_column('transactions', sa.Column('network', sa.Text(), nullable=True))
    op.alter_column('transactions', 'status',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.alter_column('transactions', 'transaction_type',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.create_index(op.f('ix_transactions_receiver_id'), 'transactions', ['receiver_id'], unique=False)
    op.create_index(op.f('ix_transactions_sender_id'), 'transactions', ['sender_id'], unique=False)
    op.create_index(op.f('ix_transactions_user_id'), 'transactions', ['user_id'], unique=False)
    op.create_foreign_key(None, 'transactions', 'user', ['receiver_id'], ['id'])
    op.create_foreign_key(None, 'transactions', 'coins', ['coin_id'], ['id'])
    op.create_foreign_key(None, 'transactions', 'user', ['sender_id'], ['id'])
    op.drop_column('transactions', 'address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('address', mysql.TEXT(), nullable=True))
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_index(op.f('ix_transactions_user_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_sender_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_receiver_id'), table_name='transactions')
    op.alter_column('transactions', 'transaction_type',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.alter_column('transactions', 'status',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.drop_column('transactions', 'network')
    op.drop_column('transactions', 'sender_fee')
    op.drop_column('transactions', 'receiver_fee')
    op.drop_column('transactions', 'receiver_address')
    op.drop_column('transactions', 'coin_id')
    op.drop_column('transactions', 'receiver_id')
    op.drop_column('transactions', 'sender_id')
    op.drop_table('admin_wallets')
    # ### end Alembic commands ###
