name: Deploy Python App to cPanel

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Upload files via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_HOST }}  # Add your cPanel FTP server
          username: ${{ secrets.FTP_USERNAME }}  # Your FTP username (add as secret in GitHub)
          password: ${{ secrets.FTP_PASSWORD }}  # Your FTP password (add as secret in GitHub)

      - name: Restart Python App via cPanel API
        env:
          CPANEL_USER: ${{ secrets.CPANEL_USER }}
          CPANEL_PASSWORD: ${{ secrets.CPANEL_PASSWORD }}
          CPANEL_DOMAIN: ${{ secrets.CPANEL_DOMAIN }}
        run: |
          curl -u $CPANEL_USER:$CPANEL_PASSWORD https://$CPANEL_DOMAIN:2083/execute/Python/restart --data-raw "app=core"
